version: 2
jobs:
    build:
        docker:
            - image: byuoitav/build-env:master
        environment:
            GOROOT: ""
            GOPATH: "${HOME}/.go_project"
            BUILD_PATH: "${GOPATH}/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"

        working_directory: /go/src/github.com/byuoitav/device-monitoring-microservice

        steps:
            - checkout
            - run: echo 'export ${GOPATH}/bin:${PATH}'>> $BASH_ENV
            - setup_remote_docker
            - run: rm -rf ~/.go_workspace
            - run: go get -u github.com/FiloSottile/gvt
            - run: npm install -g @angular/cli
            - run: mkdir -p ~/.go_project/src/github.com/${CIRCLE_PROJECT_USERNAME}
            - run: ln -s ${HOME}/${CIRCLE_PROJECT_REPONAME} ${BUILD_PATH}
            - run: cd $BUILD_PATH && make deps
            - run: cd $BUILD_PATH && make build
            - run: cd $BUILD_PATH && make test
            - deploy:
                command:
                    - cd $BUILD_PATH && make docke
