package mics

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"strconv"
	"time"

	"github.com/byuoitav/av-api/dbo"
	"github.com/byuoitav/av-api/status"
	sm "github.com/byuoitav/device-monitoring-microservice/statemonitoring"
	ei "github.com/byuoitav/event-router-microservice/eventinfrastructure"
)

var ticker time.Ticker

const STATUS_OK = 200

func GetMicBatteries(interval time.Duration, shureAddr, format, building, room string) {

	//start by getting the Shure device from the database
	shure, err := dbo.GetDevicesByBuildingAndRoomAndRole(building, room, "Receiver")
	if err != nil {
		errorMessage := "Could not find Shure device in room " + err.Error()
		log.Printf(errorMessage)
		sm.PublishError(errorMessage, ei.AUTOGENERATED)
		return
	}

	//validate that there is only one shure in a room
	if len(shure) != 1 {
		errorMessage := "Invalid Shure receiver configuration detected"
		log.Printf(errorMessage)
		sm.PublishError(errorMessage, ei.AUTOGENERATED)
		return
	}

	ticker := time.NewTicker(interval)

	go func() {
		for _ = range ticker.C {

			//for each configured port query mic power status (assume each port configuration is a mic)
			for _, port := range shure[0].Ports {

				//query power status
				power, err := QueryMicPower(port.Name, shureAddr)
				if err != nil {
					sm.PublishError("Error querying mic power status: "+err.Error(), ei.AUTOGENERATED)
				}

				if power.Power == "on" {

					battery, err := QueryMicBattery(shureAddr, port.Name, format)
					if err != nil {
						sm.PublishError("Error querying mic battery status: "+err.Error(), ei.AUTOGENERATED)
					}

					batteryString := strconv.Itoa(battery.Battery)
					err = sm.SendEvent(ei.DETAILSTATE, ei.AUTOGENERATED, port.Source, building, room, "mic battery", batteryString, false)
					if err != nil {
						sm.PublishError("Error publishing event", ei.AUTOGENERATED)
					}
				}

			}
		}
	}()

}

func QueryMicPower(address, channel string) (status.PowerStatus, error) {
	return status.PowerStatus{}, nil

	address = fmt.Sprintf("http://%s/%s/power/status", address, channel)

	response, err := http.Get(address)
	if err != nil {
		return status.PowerStatus{}, err
	} else if response.StatusCode != STATUS_OK {
		return status.PowerStatus{}, errors.New("Non-200 response from shure audio microservice")
	}

	body, err := ioutil.ReadAll(response.Body)
	if err != nil {
		return status.PowerStatus{}, err
	}

	var power status.PowerStatus
	err = json.Unmarshal(body, &power)
	if err != nil {
		return status.PowerStatus{}, err
	}

	return power, nil
}

func QueryMicBattery(address, channel, format string) (status.Battery, error) {

	//build address
	address = fmt.Sprintf("http://%s/%s/battery/%s", address, channel, format)

	//send request
	response, err := http.Get(address)
	if err != nil {
		return status.Battery{}, err
	} else if response.StatusCode != STATUS_OK {
		return status.Battery{}, errors.New("Non-200 response from shure audio microservice")
	}

	body, err := ioutil.ReadAll(response.Body)
	if err != nil {
		return status.Battery{}, err
	}

	var battery status.Battery
	err = json.Unmarshal(body, &battery)
	if err != nil {
		return status.Battery{}, err
	}

	return battery, nil

}
